### ISSUE TITLE
Would you mind cutting a new release with the two changes this month?

### ISSUE THREAD

**Issue by smk4664** [jrief/django-entangled#15]
Thanks for merging the fix in! Would you mind cutting a new release with the two changes this month?

_Originally posted by @smk4664 in https://github.com/jrief/django-entangled/issues/13#issuecomment-1036243980_

**Comment by jrief** [comment]
sure, but please add those two changes to the changelog.

**Comment by jrief** [comment]
done, but as 0.5.1 since no new features have been added.
