### ISSUE TITLE
Are only standard form fields supported?

### ISSUE THREAD

**Issue by marksweb** [jrief/django-entangled#18]
I'm trying to create a model to store colours for theming a page, so I'm using [django-colorfield](https://pypi.org/project/django-colorfield/) to display colour values. The fields provided by this app are a subclass of `CharField` so nothing too complex.

I'm seeing an error on the model/field check;

`AssertionError: Field primary listed in `ThemeForm.Meta.entangled_fields['config']` is missing in Form declaration`

My model is fairly simple;

```
class Theme(models.Model):
    """ Theme model for holding CSS styles """

    class Meta:
        app_label = 'theme'
        verbose_name = gettext("Theme")
        verbose_name_plural = gettext('Themes')

    name = models.CharField(max_length=100)
    config = models.JSONField(default=dict)
```

And my form;

```
from django import forms
from django.utils.translation import gettext_lazy as _

from colorfield.fields import ColorField
from entangled.forms import EntangledModelForm

from ..models import Theme


class ThemeForm(EntangledModelForm):
    """ Theme form """

    class Meta:
        model = Theme
        entangled_fields = {
            "config": [
                "primary",
                "secondary",
            ]
        }
        untangled_fields = ("name",)

    name = forms.CharField(
        label=_("Name"),
        max_length=100
    )
    primary = ColorField(default='#766df4')
    secondary = ColorField(default='#f7f7fc')
```

If I change `primary` or `secondary` to a standard `CharField()` then this error goes away.

**Comment by jrief** [comment]
Hmm, I have to build an environment to reproduce this.

Does `ColorField` inherit from Django's `Field` class? I always believed that django-entangled supports all Django Field types. For instance, I sometimes use the django-phonenumber-field. This works seamlessly with django-entangled. Never tested django-colorfield though.

Hint: If you use a `CharField` with a `TextInput` widget and set `attrs={'type': 'color'}` you get the browser's built-in color picker. Probably not what you really want, but still better than colors in hex.

**Comment by marksweb** [comment]
@jrief Actually looking at the field in more detail, it's a model field that I've included in my form. I missed the details because it's provided in a generic `fields.py` 🤦‍♂️  

I'll close this & construct the intended form fields with their colour widget. I'm sure then it'll be happy.
