### ISSUE TITLE
Inheritance of EntangledModelForms

### ISSUE THREAD

**Issue by fsbraun** [jrief/django-entangled#8]
I think I understand the usage of `EntangledModelForm` and `EntangledModelFormMixin`. Can I subclass an entangled form to add additional entangled fields? If yes, how so? Thanks for helping out!

**Comment by jrief** [comment]
Yes, that's the purpose. In fact, in djangocms-cascade I do that all the time.
If you add new field in an inherited class, those fields are added automatically to the form.
