### ISSUE TITLE
How to add list of items?

### ISSUE THREAD

**Issue by nikolas-dev** [jrief/django-entangled#9]
I want to add like below. How can I achieve this?
```
[
  {
    "name": "Test 1",
    "roll": 1,
    "section": "A"
  },
  {
    "name": "Test 2",
    "roll": 2,
    "section": "A"
  }
]
```

**Comment by jrief** [comment]
I don't understand what you mean.

**Comment by nikolas-dev** [comment]
I've my model:
```
class SportsGroup(models.Model):
    group_name = models.CharField(max_length=30)
    details = models.JSONField(default=list)
```
my form:

```
class SportsGroupForm(EntangledModelForm):
    name = forms.CharField(required=True)
    roll = forms.CharField(required=True)
    section = forms.CharField(required=True)

    class Meta:
        model = Customer
        entangled_fields = {'details': ['name', 'roll', 'section']}
        untangled_fields = ('group_name',)
```
Now it saving data like:
```
{
  "details": {
    "name": "Test 1",
    "roll": 1,
    "section": "A"
  }
}
```
Need Multiple People add inside details like below
```
{
  "group_name": "Hello Group",
  "details": [
    {
      "name": "Test 1",
      "roll": 1,
      "section": "A"
    },
    {
      "name": "Test 2",
      "roll": 2,
      "section": "A"
    }
  ]
}
```

**Comment by jrief** [comment]
You write

> Now it saving data like:
> ```{
>    "details": {
>      "name": "Test 1",
>      "roll": 1,
>      "section": "A"
>   }
>}

but where does this JSON come from? I mean, if you render the form and enter some data, then you submit the form using some kind of encoding, such as `application/x-www-form-urlencoded` or `multipart/form-data`, not JSON.

**Comment by nikolas-dev** [comment]
see details is my model form attribute. Is there any way using formset?

**Comment by jrief** [comment]
Closing for not providing meaningful information.
